-- for any new cron expression please validate in http://www.cronmaker.com/
CREATE TABLE SCHEDULING_INFO (
    SCHEDULE_NAME varchar(255),
    SCHEDULE_EXPRESSION varchar(255)
);

INSERT INTO SCHEDULING_INFO (SCHEDULE_NAME, SCHEDULE_EXPRESSION)
VALUES ('PER_QUATER_MINUTE', '0/15 * * 1/1 * ? *');
INSERT INTO SCHEDULING_INFO (SCHEDULE_NAME, SCHEDULE_EXPRESSION)
VALUES ('PER_MINUTE', '0 0/1 * 1/1 * ? *');
INSERT INTO SCHEDULING_INFO (SCHEDULE_NAME, SCHEDULE_EXPRESSION)
VALUES ('PER_THIRTY_MINUTE', '0 0/30 * 1/1 * ? *');
INSERT INTO SCHEDULING_INFO (SCHEDULE_NAME, SCHEDULE_EXPRESSION)
VALUES ('PER_HOUR', '0 0 0/1 1/1 * ? *');
INSERT INTO SCHEDULING_INFO (SCHEDULE_NAME, SCHEDULE_EXPRESSION)
VALUES ('OFFICE_HOUR', '0 */1 9,18 1/1 * ? *');
INSERT INTO SCHEDULING_INFO (SCHEDULE_NAME, SCHEDULE_EXPRESSION)
VALUES ('EVERYDAY_AT_NOON', '0 0 12 1/1 * ? *');


CREATE TABLE STEP_EXECUTION_CONDITION (
    STEP_NAME VARCHAR(255),
    EXECUTE_CONDITION VARCHAR(255)
);

INSERT INTO STEP_EXECUTION_CONDITION (STEP_NAME, EXECUTE_CONDITION)
VALUES ('JOB_STEP1', 'PROCEED');
INSERT INTO STEP_EXECUTION_CONDITION (STEP_NAME, EXECUTE_CONDITION)
VALUES ('JOB_STEP2', 'PROCEED');
INSERT INTO STEP_EXECUTION_CONDITION (STEP_NAME, EXECUTE_CONDITION)
VALUES ('JOB_STEP3', 'PROCEED');